<a href="https://colab.research.google.com/github/Jia-Yu-Yu/pycs4001/blob/main/class04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **物件導向**

In [1]:
#class Person : #要大寫
#  def __init__(self):  #init: 建構子 constructor
#    self.name = "Thousand"  # Person 的第一個屬性：名字
#    self.gender = "Male"    # Person 的第二個屬性：性別
#    print("This is Person Class")

In [2]:
# 物件化（實體化）（實體化）instance
#p1 = Person() 

This is Person Class


In [3]:
#print(p1.name)
#print(p1.gender)

Thousand
Male


In [1]:
class Person : 
  # 建構子 constructor
  def __init__(self, name, gender):  
    self.n = name  
    self.g = gender    
    print("This is Person Class")

  # instance method
  def introduction(self):
    print(f"Hello my name is {self.n}")

In [2]:
p1 = Person(name = "Thousand", gender = "Male")
p2 = Person(name = "Allie", gender = "Female")

This is Person Class
This is Person Class


In [3]:
print(p1.n, p1.g)
print(p2.n, p2.g)

Thousand Male
Allie Female


In [4]:
p1.introduction()

Hello my name is Thousand


In [5]:
p2.introduction()

Hello my name is Allie


In [1]:
class Warrior:
  def __init__(self, name, gender, weapon = "bat"):
    self.lv = 1
    self.exp = 0
    self.n = name
    self.g = gender
    self.w = weapon
    self.sp = 100
    print("This is Warrior class.")
  
  def __str__(self):
    return f"Name: {self.n}, Gender: {self.g}, Weapon: {self.w}, Level: {self.lv}, Exp: {self.exp} "
  
  def attack(self,enemy):
    self.exp +=40
    enemy.hp -=1
    self.level_up()  #呼叫另一個method
    print(f"{self.n} attacked! Level: {self.lv}, Exp:{self.exp}")
 
  def level_up(self):
    if self.exp >= 100 :
      self.lv += 1
      self.exp -= 100
      print(f"{self.n} Level up!!! ")

In [ ]:
class Magician:
  def __init__(self, name, gender, weapon = "bat"):
    self.lv = 1
    self.exp = 0
    self.n = name
    self.g = gender
    self.w = weapon
    self.mp = 100
    
  
  def __str__(self):
    return f"Name: {self.n}, Gender: {self.g}, Weapon: {self.w}, Level: {self.lv}, Exp: {self.exp} "
  
  def attack(self,enemy):
    self.exp +=40
    enemy.hp -=1
    self.level_up()  #呼叫另一個method
    print(f"{self.n} attacked! Level: {self.lv}, Exp:{self.exp}")
 
  def level_up(self):
    if self.exp >= 100 :
      self.lv += 1
      self.exp -= 100
      print(f"{self.n} Level up!!! ")

In [2]:
class Enemy:
  def __init__(self):
    self.name = "Monster"
    self.hp = 100

In [3]:
w1 = Warrior(name = "Thousand", gender = "Male", weapon = "Sword")
w2 = Warrior(name = "Allie", gender = "Female", weapon = "Longbow")

This is Warrior class.
This is Warrior class.


In [4]:
e = Enemy()

In [5]:
print(f"Warrior: {w1} ")

Warrior: Name: Thousand, Gender: Male, Weapon: Sword, Level: 1, Exp: 0  


In [6]:
for i in range(5):
  w1.attack(enemy = e)

Thousand attacked! Level: 1, Exp:40
Thousand attacked! Level: 1, Exp:80
Thousand Level up!!! 
Thousand attacked! Level: 2, Exp:20
Thousand attacked! Level: 2, Exp:60
Thousand Level up!!! 
Thousand attacked! Level: 3, Exp:0


In [7]:
e.hp

95

# **繼承 (Inheritance)**

In [1]:
#super
class Character:
  def __init__(self, name, gender, weapon = "bat"):
    self.lv = 1
    self.exp = 0
    self.n = name
    self.g = gender
    self.w = weapon
    print("This is Character class.")

  def __str__(self):
    return f"Name: {self.n}, Gender: {self.g}, Weapon: {self.w}, Level: {self.lv}, Exp: {self.exp} "
  
  def attack(self,enemy):
    self.exp +=40
    enemy.hp -=1
    self.level_up()  #呼叫另一個method
    print(f"{self.n} attacked! Level: {self.lv}, Exp:{self.exp}")
 
  def level_up(self):
    if self.exp >= 100 :
      self.lv += 1
      self.exp -= 100
      print(f"{self.n} Level up!!! ")

In [2]:
class Enemy:
  def __init__(self):
    self.name = "Monster"
    self.hp = 100

In [3]:
#sub :Warrior.    繼承祖先的所有屬性跟特性
class Warrior(Character):
  def __init__(self, name, gender, weapon="bat"): 
    super().__init__(name, gender, weapon)  
    self.sp = 100
    print("This is Warrior Class")

  def attack(self, enemy):   #改寫super的的attack
    super().attack(enemy)
    print("w1")

  def attack(self):  #override: 把super的的attack整個改掉
    print("w1")

In [4]:
#sub: Magician.    繼承祖先的所有屬性跟特性
class Magician(Character):
  def __init__(self, name, gender, weapon="bat"): 
    super().__init__(name, gender, weapon)  
    self.mp = 100
    print("This is Magician Class")

In [5]:
w1 = Warrior(name = "Thousand", gender = "Male", weapon = "Sword")
w2 = Warrior(name = "Allie", gender = "Female", weapon = "Longbow")

This is Character class.
This is Warrior Class
This is Character class.
This is Warrior Class


In [7]:
print(w1)

Name: Thousand, Gender: Male, Weapon: Sword, Level: 1, Exp: 0 


In [6]:
print(f"Warrior: {w1} ")

Warrior: Name: Thousand, Gender: Male, Weapon: Sword, Level: 1, Exp: 0  


In [8]:
e = Enemy()

In [9]:
for i in range(5):
  w1.attack(enemy = e)

Thousand attacked! Level: 1, Exp:40
Thousand attacked! Level: 1, Exp:80
Thousand Level up!!! 
Thousand attacked! Level: 2, Exp:20
Thousand attacked! Level: 2, Exp:60
Thousand Level up!!! 
Thousand attacked! Level: 3, Exp:0


In [10]:
e.hp

95

# **Numpy**

In [11]:
import numpy as np

In [12]:
a = [1,2,3]
b = [4,5,6]
print(a+b)

[1, 2, 3, 4, 5, 6]


In [13]:
arr1 = np.array(a)
arr2 = np.array(b)
print(arr1 + arr2)

[5 7 9]


In [14]:
a = np.array([1,2,3])
b = np.array([[1.0,2.0,3.0],[3.2,5.7,8.2]])
print(f"a: {a}")
print(f"a dimension: {a.ndim}")
print(f"a shape: {a.shape}")   # 一維
print(f"a type: {a.dtype}")
print(f"b: {b}")
print(f"b dimension: {b.ndim}")
print(f"b shape: {b.shape}")   # 二維
print(f"b type: {b.dtype}")

a: [1 2 3]
a dimension: 1
a shape: (3,)
a type: int64
b: [[1.  2.  3. ]
 [3.2 5.7 8.2]]
b dimension: 2
b shape: (2, 3)
b type: float64


In [15]:
# index/slice/2D

a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a[1,2]) # 9
print(a[0,:]) # [1,2,3,4,5,6]
print(a[:,2]) # [3,9]
print(a[0,1:5:2]) # [2,4] (start,stop,step)
a[1,2] = 20
print(a)
a[:,2] = [7,8]
print(a)

9
[1 2 3 4 5 6]
[3 9]
[2 4]
[[ 1  2  3  4  5  6]
 [ 7  8 20 10 11 12]]
[[ 1  2  7  4  5  6]
 [ 7  8  8 10 11 12]]


In [16]:
# index/slice/3D

a = np.array([[[1,2],[3,5],[7,8]],
              [[1,7],[-3,2],[10,2]],
              [[6,-2],[5,-3],[7,9]],
              [[8,5],[-2,2],[26,-2]],
              [[1,-7],[-3,2],[-5,-2]],])
print(a)
print(a.shape) 
print(a[3,2,0])
print(a[:,1,:])

[[[ 1  2]
  [ 3  5]
  [ 7  8]]

 [[ 1  7]
  [-3  2]
  [10  2]]

 [[ 6 -2]
  [ 5 -3]
  [ 7  9]]

 [[ 8  5]
  [-2  2]
  [26 -2]]

 [[ 1 -7]
  [-3  2]
  [-5 -2]]]
(5, 3, 2)
26
[[ 3  5]
 [-3  2]
 [ 5 -3]
 [-2  2]
 [-3  2]]


In [ ]:
# 矩陣乘法
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[2,3,1],[5,2,1]])
print(np.matmul(a,b))  # matrix multiply

In [ ]:
# 乘法單位元素
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
identity = np.identity(3)   # 單位矩陣 3*3
print(np.matmul(a,identity))

In [17]:
# statistics
a = np.array([[92,83,56,77,98],[81,53,64,76,60]])
# a :(2,5) => axis=0 :2 , axis=1 :5  從哪個方向找最大
print(np.max(a,axis=0))
print(np.max(a,axis=1))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

[92 83 64 77 98]
[98 81]
[173 136 120 153 158]
[406 334]
