<a href="https://colab.research.google.com/github/Jia-Yu-Yu/pycs4001/blob/main/hw4_%E6%B8%B8%E4%BD%B3%E8%AB%AD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.**

In [ ]:
import numpy as np
A = np.empty(shape=(2,3))
B = np.empty(shape=(3,2))

for i in range(len(A)):
  A[i]=input().split(' ')

for i in range(len(B)):
  B[i]=input().split(' ')

print(A)
print(B)
print(np.matmul(A,B))

2 3 5
5 7 8
1 2
3 10
2 6
[[2. 3. 5.]
 [5. 7. 8.]]
[[ 1.  2.]
 [ 3. 10.]
 [ 2.  6.]]
[[ 21.  64.]
 [ 42. 128.]]


In [ ]:
import numpy as np
A = []
B = []

a = 2
b = 3

for i in range(a):
  A.append(list(map(int, input().rstrip().split())))

for i in range(b):
  B.append(list(map(int, input().rstrip().split())))

print(A)
print(B)
print(np.matmul(A,B))

2 3 5
5 7 8
1 2
3 10
2 6
[[2, 3, 5], [5, 7, 8]]
[[1, 2], [3, 10], [2, 6]]
[[ 21  64]
 [ 42 128]]


# **2.**

In [ ]:
import numpy as np
A = []
B = []
C = []

for i in range(1):
  A.append(list(map(int, input("A class: ").rstrip().split())))

for i in range(1):
  B.append(list(map(int, input("B class: ").rstrip().split())))

for i in range(1):
  C.append(list(map(int, input("C class: ").rstrip().split())))

A_sum = int(np.sum(A,axis=1))
A_max = int(np.max(A,axis=1))
B_sum = int(np.sum(B,axis=1))
B_max = int(np.max(B,axis=1))
C_sum = int(np.sum(C,axis=1))
C_max = int(np.max(C,axis=1))

print()
print(f"A class 總和：{A_sum} , 最大：{A_max}")
print(f"B class 總和：{B_sum} , 最大：{B_max}")
print(f"C class 總和：{C_sum} , 最大：{C_max}")

A class: 32 57 89
B class: 88 93 20
C class: 82 75 88

A class 總和：178 , 最大：89
B class 總和：201 , 最大：89
C class 總和：245 , 最大：89
